# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenywordsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denywords', models.CharField(max_length=1000, verbose_name='Deny Keywords  (Eg: Contract,W2,Fulltime )')),
            ],
        ),
        migrations.AddField(
            model_name='keyword_search',
            name='deny_filters',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobs.DenywordsList'),
        ),
    ]
