# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_UID', models.CharField(max_length=50)),
                ('mail_KEY', models.CharField(max_length=50)),
                ('mail_from', models.EmailField(max_length=300)),
                ('mail_title', models.CharField(max_length=200)),
                ('mail_discription', models.CharField(max_length=5000)),
                ('date_recieved', models.CharField(max_length=200)),
                ('sync_time', models.CharField(max_length=200)),
                ('last_updated', models.CharField(max_length=200)),
                ('status', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mail_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ID', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='all_mails',
            name='mail_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.mail_id'),
        ),
    ]
